name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          zip -r app.zip .
          aws elasticbeanstalk create-application-version \
            --application-name backend-tomangg \
            --version-label v1.0.0 \
            --source-bundle S3Bucket="YOUR_S3_BUCKET_NAME",S3Key="app.zip"
          aws elasticbeanstalk update-environment \
            --environment-name backend-tomangg-env \
            --version-label v1.0.0
